web:
    image: nguyenminhduc24396/homestead
    restart: unless-stopped
    ports:
        - "8000:80" # web
        - "2222:22" # ssh
    volumes:
        - ~/.composer:/home/homestead/.composer # composer caching
        - ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
        - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
        - ~/Documents:/apps # all apps
        - ~/apps/volumes/nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
        - ~/apps/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
        - ~/volumes/nginx/ssl:/etc/nginx/ssl
    links:
        - mysql
mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
        - "3307:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - ~/volumes/mysql:/var/lib/mysql
adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
